language: node_js
node_js:
  - 5
  - 6

sudo: false

addons:
  firefox: "39.0"

os:
  - linux
  - osx

matrix:
  exclude:
    - os: osx
      node_js: 5
    - os: osx
      node_js: 6

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew outdated xctool || brew upgrade xctool; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export CHROME_BIN=chromium-browser; fi  # Karma CI
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew cask install google-chrome; fi  # Karma CI
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export DISPLAY=:99.0; fi

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sh -e /etc/init.d/xvfb start; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then nohup bash -c "webdriver-manager start 2>&1 &"; fi  # Protractor CI

after_failure:
  - cat /home/travis/build/deviantjs/angular2-seed-material2/npm-debug.log

branches:
  only: master

cache:
  directories: node_modules

script:
  - npm run tests.all
